Algoritmo "Lista1E1"
// Disciplina   : Lógica de Programação I
// Professor   : Ivan J. Borchardt 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/9/2022
Var
// Seção de Declarações das variáveis 

    nome : caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva("Informe seu nome: ")
   leia(nome)
   
   escreva("Olá ", nome, ", é um prazer te conhecer!")


Fimalgoritmo